using System.Collections.Generic;

namespace Util.Extras.Helpers
{
    /// <summary>
    /// 常量
    /// </summary>
    public static class Const
    {

        #region 数字

        /// <summary>
        /// 阿拉伯数字
        /// </summary>
        public const string ArabicNumbers = "0123456789";

        /// <summary>
        /// 汉字数字
        /// </summary>
        public const string ChineseNumbers = "零壹贰叁肆伍陆柒捌玖";

        #endregion

        #region 英文字母

        /// <summary>
        /// 小写英文字母
        /// </summary>
        public const string Lowercase = "abcdefghijklmnopqrstuvwxyz";

        /// <summary>
        /// 大写英文字母
        /// </summary>
        public const string Uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        #endregion

        #region 数字及字母

        /// <summary>
        /// 数字及字母
        /// </summary>
        public static readonly char[] NumberAndBetter = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z' };

        #endregion

        #region FileExtensionDict(文件扩展类型字典)

        /// <summary>
        /// 文件扩展类型字典
        /// </summary>
        public static Dictionary<string, string> FileExtensionDict => new Dictionary<string, string>()
        {
            {".*", "application/octet-stream"},
            {".tif", "image/tiff"},
            {".001", "application/x-001"},
            {".301", "application/x-301"},
            {".323", "text/h323"},
            {".906", "application/x-906"},
            {".907", "drawing/907"},
            {".a11", "application/x-a11"},
            {".acp", "audio/x-mei-aac"},
            {".ai", "application/postscript"},
            {".aif", "audio/aiff"},
            {".aifc", "audio/aiff"},
            {".aiff", "audio/aiff"},
            {".anv", "application/x-anv"},
            {".asa", "text/asa"},
            {".asf", "video/x-ms-asf"},
            {".asp", "text/asp"},
            {".asx", "video/x-ms-asf"},
            {".au", "audio/basic"},
            {".avi", "video/avi"},
            {".awf", "application/vnd.adobe.workflow"},
            {".biz", "text/xml"},
            {".bmp", "application/x-bmp"},
            {".bot", "application/x-bot"},
            {".c4t", "application/x-c4t"},
            {".c90", "application/x-c90"},
            {".cal", "application/x-cals"},
            {".cat", "application/vnd.ms-pki.seccat"},
            {".cdf", "application/x-netcdf"},
            {".cdr", "application/x-cdr"},
            {".cel", "application/x-cel"},
            {".cer", "application/x-x509-ca-cert"},
            {".cg4", "application/x-g4"},
            {".cgm", "application/x-cgm"},
            {".cit", "application/x-cit"},
            {".class", "java/*"},
            {".cml", "text/xml"},
            {".cmp", "application/x-cmp"},
            {".cmx", "application/x-cmx"},
            {".cot", "application/x-cot"},
            {".crl", "application/pkix-crl"},
            {".crt", "application/x-x509-ca-cert"},
            {".csi", "application/x-csi"},
            {".css", "text/css"},
            {".cut", "application/x-cut"},
            {".dbf", "application/x-dbf"},
            {".dbm", "application/x-dbm"},
            {".dbx", "application/x-dbx"},
            {".dcd", "text/xml"},
            {".dcx", "application/x-dcx"},
            {".der", "application/x-x509-ca-cert"},
            {".dgn", "application/x-dgn"},
            {".dib", "application/x-dib"},
            {".dll", "application/x-msdownload"},
            {".doc", "application/msword"},
            {".dot", "application/msword"},
            {".drw", "application/x-drw"},
            {".dtd", "text/xml"},
            {".dwf", "Model/vnd.dwf"},
            {".dwg", "application/x-dwg"},
            {".dxb", "application/x-dxb"},
            {".dxf", "application/x-dxf"},
            {".edn", "application/vnd.adobe.edn"},
            {".emf", "application/x-emf"},
            {".eml", "message/rfc822"},
            {".ent", "text/xml"},
            {".epi", "application/x-epi"},
            {".eps", "application/x-ps"},
            {".etd", "application/x-ebx"},
            {".exe", "application/x-msdownload"},
            {".fax", "image/fax"},
            {".fdf", "application/vnd.fdf"},
            {".fif", "application/fractals"},
            {".fo", "text/xml"},
            {".frm", "application/x-frm"},
            {".g4", "application/x-g4"},
            {".gbr", "application/x-gbr"},
            {".", "application/x-"},
            {".gif", "image/gif"},
            {".gl2", "application/x-gl2"},
            {".gp4", "application/x-gp4"},
            {".hgl", "application/x-hgl"},
            {".hmr", "application/x-hmr"},
            {".hpg", "application/x-hpgl"},
            {".hpl", "application/x-hpl"},
            {".hqx", "application/mac-binhex40"},
            {".hrf", "application/x-hrf"},
            {".hta", "application/hta"},
            {".htc", "text/x-component"},
            {".htm", "text/html"},
            {".html", "text/html"},
            {".htt", "text/webviewhtml"},
            {".htx", "text/html"},
            {".icb", "application/x-icb"},
            {".ico", "image/x-icon"},
            {".iff", "application/x-iff"},
            {".ig4", "application/x-g4"},
            {".igs", "application/x-igs"},
            {".iii", "application/x-iphone"},
            {".img", "application/x-img"},
            {".ins", "application/x-internet-signup"},
            {".isp", "application/x-internet-signup"},
            {".IVF", "video/x-ivf"},
            {".java", "java/*"},
            {".jfif", "image/jpeg"},
            {".jpe", "application/x-jpe"},
            {".jpeg", "image/jpeg"},
            {".jpg", "image/jpeg"},
            {".js", "application/x-javascript"},
            {".jsp", "text/html"},
            {".la1", "audio/x-liquid-file"},
            {".lar", "application/x-laplayer-reg"},
            {".latex", "application/x-latex"},
            {".lavs", "audio/x-liquid-secure"},
            {".lbm", "application/x-lbm"},
            {".lmsff", "audio/x-la-lms"},
            {".ls", "application/x-javascript"},
            {".ltr", "application/x-ltr"},
            {".m1v", "video/x-mpeg"},
            {".m2v", "video/x-mpeg"},
            {".m3u", "audio/mpegurl"},
            {".m4e", "video/mpeg4"},
            {".mac", "application/x-mac"},
            {".man", "application/x-troff-man"},
            {".math", "text/xml"},
            {".mdb", "application/msaccess"},
            {".mfp", "application/x-shockwave-flash"},
            {".mht", "message/rfc822"},
            {".mhtml", "message/rfc822"},
            {".mi", "application/x-mi"},
            {".mid", "audio/mid"},
            {".midi", "audio/mid"},
            {".mil", "application/x-mil"},
            {".mml", "text/xml"},
            {".mnd", "audio/x-musicnet-download"},
            {".mns", "audio/x-musicnet-stream"},
            {".mocha", "application/x-javascript"},
            {".movie", "video/x-sgi-movie"},
            {".mp1", "audio/mp1"},
            {".mp2", "audio/mp2"},
            {".mp2v", "video/mpeg"},
            {".mp3", "audio/mp3"},
            {".mp4", "video/mpeg4"},
            {".mpa", "video/x-mpg"},
            {".mpd", "application/vnd.ms-project"},
            {".mpe", "video/x-mpeg"},
            {".mpeg", "video/mpg"},
            {".mpg", "video/mpg"},
            {".mpga", "audio/rn-mpeg"},
            {".mpp", "application/vnd.ms-project"},
            {".mps", "video/x-mpeg"},
            {".mpt", "application/vnd.ms-project"},
            {".mpv", "video/mpg"},
            {".mpv2", "video/mpeg"},
            {".mpw", "application/vnd.ms-project"},
            {".mpx", "application/vnd.ms-project"},
            {".mtx", "text/xml"},
            {".mxp", "application/x-mmxp"},
            {".net", "image/pnetvue"},
            {".nrf", "application/x-nrf"},
            {".nws", "message/rfc822"},
            {".odc", "text/x-ms-odc"},
            {".out", "application/x-out"},
            {".p10", "application/pkcs10"},
            {".p12", "application/x-pkcs12"},
            {".p7b", "application/x-pkcs7-certificates"},
            {".p7c", "application/pkcs7-mime"},
            {".p7m", "application/pkcs7-mime"},
            {".p7r", "application/x-pkcs7-certreqresp"},
            {".p7s", "application/pkcs7-signature"},
            {".pc5", "application/x-pc5"},
            {".pci", "application/x-pci"},
            {".pcl", "application/x-pcl"},
            {".pcx", "application/x-pcx"},
            {".pdf", "application/pdf"},
            {".pdx", "application/vnd.adobe.pdx"},
            {".pfx", "application/x-pkcs12"},
            {".pgl", "application/x-pgl"},
            {".pic", "application/x-pic"},
            {".pko", "application/vnd.ms-pki.pko"},
            {".pl", "application/x-perl"},
            {".plg", "text/html"},
            {".pls", "audio/scpls"},
            {".plt", "application/x-plt"},
            {".png", "image/png"},
            {".pot", "application/vnd.ms-powerpoint"},
            {".ppa", "application/vnd.ms-powerpoint"},
            {".ppm", "application/x-ppm"},
            {".pps", "application/vnd.ms-powerpoint"},
            {".ppt", "application/vnd.ms-powerpoint"},
            {".pr", "application/x-pr"},
            {".prf", "application/pics-rules"},
            {".prn", "application/x-prn"},
            {".prt", "application/x-prt"},
            {".ps", "application/x-ps"},
            {".ptn", "application/x-ptn"},
            {".pwz", "application/vnd.ms-powerpoint"},
            {".r3t", "text/vnd.rn-realtext3d"},
            {".ra", "audio/vnd.rn-realaudio"},
            {".ram", "audio/x-pn-realaudio"},
            {".ras", "application/x-ras"},
            {".rat", "application/rat-file"},
            {".rdf", "text/xml"},
            {".rec", "application/vnd.rn-recording"},
            {".red", "application/x-red"},
            {".rgb", "application/x-rgb"},
            {".rjs", "application/vnd.rn-realsystem-rjs"},
            {".rjt", "application/vnd.rn-realsystem-rjt"},
            {".rlc", "application/x-rlc"},
            {".rle", "application/x-rle"},
            {".rm", "application/vnd.rn-realmedia"},
            {".rmf", "application/vnd.adobe.rmf"},
            {".rmi", "audio/mid"},
            {".rmj", "application/vnd.rn-realsystem-rmj"},
            {".rmm", "audio/x-pn-realaudio"},
            {".rmp", "application/vnd.rn-rn_music_package"},
            {".rms", "application/vnd.rn-realmedia-secure"},
            {".rmvb", "application/vnd.rn-realmedia-vbr"},
            {".rmx", "application/vnd.rn-realsystem-rmx"},
            {".rnx", "application/vnd.rn-realplayer"},
            {".rp", "image/vnd.rn-realpix"},
            {".rpm", "audio/x-pn-realaudio-plugin"},
            {".rsml", "application/vnd.rn-rsml"},
            {".rt", "text/vnd.rn-realtext"},
            {".rtf", "application/msword"},
            {".rv", "video/vnd.rn-realvideo"},
            {".sam", "application/x-sam"},
            {".sat", "application/x-sat"},
            {".sdp", "application/sdp"},
            {".sdw", "application/x-sdw"},
            {".sit", "application/x-stuffit"},
            {".slb", "application/x-slb"},
            {".sld", "application/x-sld"},
            {".slk", "drawing/x-slk"},
            {".smi", "application/smil"},
            {".smil", "application/smil"},
            {".smk", "application/x-smk"},
            {".snd", "audio/basic"},
            {".sol", "text/plain"},
            {".sor", "text/plain"},
            {".spc", "application/x-pkcs7-certificates"},
            {".spl", "application/futuresplash"},
            {".spp", "text/xml"},
            {".ssm", "application/streamingmedia"},
            {".sst", "application/vnd.ms-pki.certstore"},
            {".stl", "application/vnd.ms-pki.stl"},
            {".stm", "text/html"},
            {".sty", "application/x-sty"},
            {".svg", "text/xml"},
            {".swf", "application/x-shockwave-flash"},
            {".tdf", "application/x-tdf"},
            {".tg4", "application/x-tg4"},
            {".tga", "application/x-tga"},
            {".tiff", "image/tiff"},
            {".tld", "text/xml"},
            {".top", "drawing/x-top"},
            {".torrent", "application/x-bittorrent"},
            {".tsd", "text/xml"},
            {".txt", "text/plain"},
            {".uin", "application/x-icq"},
            {".uls", "text/iuls"},
            {".vcf", "text/x-vcard"},
            {".vda", "application/x-vda"},
            {".vdx", "application/vnd.visio"},
            {".vml", "text/xml"},
            {".vpg", "application/x-vpeg005"},
            {".vsd", "application/vnd.visio"},
            {".vss", "application/vnd.visio"},
            {".vst", "application/vnd.visio"},
            {".vsw", "application/vnd.visio"},
            {".vsx", "application/vnd.visio"},
            {".vtx", "application/vnd.visio"},
            {".vxml", "text/xml"},
            {".wav", "audio/wav"},
            {".wax", "audio/x-ms-wax"},
            {".wb1", "application/x-wb1"},
            {".wb2", "application/x-wb2"},
            {".wb3", "application/x-wb3"},
            {".wbmp", "image/vnd.wap.wbmp"},
            {".wiz", "application/msword"},
            {".wk3", "application/x-wk3"},
            {".wk4", "application/x-wk4"},
            {".wkq", "application/x-wkq"},
            {".wks", "application/x-wks"},
            {".wm", "video/x-ms-wm"},
            {".wma", "audio/x-ms-wma"},
            {".wmd", "application/x-ms-wmd"},
            {".wmf", "application/x-wmf"},
            {".wml", "text/vnd.wap.wml"},
            {".wmv", "video/x-ms-wmv"},
            {".wmx", "video/x-ms-wmx"},
            {".wmz", "application/x-ms-wmz"},
            {".wp6", "application/x-wp6"},
            {".wpd", "application/x-wpd"},
            {".wpg", "application/x-wpg"},
            {".wpl", "application/vnd.ms-wpl"},
            {".wq1", "application/x-wq1"},
            {".wr1", "application/x-wr1"},
            {".wri", "application/x-wri"},
            {".wrk", "application/x-wrk"},
            {".ws", "application/x-ws"},
            {".ws2", "application/x-ws"},
            {".wsc", "text/scriptlet"},
            {".wsdl", "text/xml"},
            {".wvx", "video/x-ms-wvx"},
            {".xdp", "application/vnd.adobe.xdp"},
            {".xdr", "text/xml"},
            {".xfd", "application/vnd.adobe.xfd"},
            {".xfdf", "application/vnd.adobe.xfdf"},
            {".xhtml", "text/html"},
            {".xls", "application/vnd.ms-excel"},
            {".xlw", "application/x-xlw"},
            {".xml", "text/xml"},
            {".xpl", "audio/scpls"},
            {".xq", "text/xml"},
            {".xql", "text/xml"},
            {".xquery", "text/xml"},
            {".xsd", "text/xml"},
            {".xsl", "text/xml"},
            {".xslt", "text/xml"},
            {".xwd", "application/x-xwd"},
            {".x_b", "application/x-x_b"},
            {".sis", "application/vnd.symbian.install"},
            {".sisx", "application/vnd.symbian.install"},
            {".x_t", "application/x-x_t"},
            {".ipa", "application/vnd.iphone"},
            {".apk", "application/vnd.android.package-archive"},
            {".xap", "application/x-silverlight-app"}
        };

        #endregion

        #region SpellLetter(拼音字母数组)

        /// <summary>
        /// 拼音字母数组
        /// </summary>
        public static string[] SpellLetter = new string[]
        {
            "A", "Ai", "An", "Ang", "Ao", "Ba", "Bai", "Ban", "Bang", "Bao", "Bei", "Ben",
            "Beng", "Bi", "Bian", "Biao", "Bie", "Bin", "Bing", "Bo", "Bu", "Ba", "Cai", "Can",
            "Cang", "Cao", "Ce", "Ceng", "Cha", "Chai", "Chan", "Chang", "Chao", "Che", "Chen", "Cheng",
            "Chi", "Chong", "Chou", "Chu", "Chuai", "Chuan", "Chuang", "Chui", "Chun", "Chuo", "Ci", "Cong",
            "Cou", "Cu", "Cuan", "Cui", "Cun", "Cuo", "Da", "Dai", "Dan", "Dang", "Dao", "De",
            "Deng", "Di", "Dian", "Diao", "Die", "Ding", "Diu", "Dong", "Dou", "Du", "Duan", "Dui",
            "Dun", "Duo", "E", "En", "Er", "Fa", "Fan", "Fang", "Fei", "Fen", "Feng", "Fo",
            "Fou", "Fu", "Ga", "Gai", "Gan", "Gang", "Gao", "Ge", "Gei", "Gen", "Geng", "Gong",
            "Gou", "Gu", "Gua", "Guai", "Guan", "Guang", "Gui", "Gun", "Guo", "Ha", "Hai", "Han",
            "Hang", "Hao", "He", "Hei", "Hen", "Heng", "Hong", "Hou", "Hu", "Hua", "Huai", "Huan",
            "Huang", "Hui", "Hun", "Huo", "Ji", "Jia", "Jian", "Jiang", "Jiao", "Jie", "Jin", "Jing",
            "Jiong", "Jiu", "Ju", "Juan", "Jue", "Jun", "Ka", "Kai", "Kan", "Kang", "Kao", "Ke",
            "Ken", "Keng", "Kong", "Kou", "Ku", "Kua", "Kuai", "Kuan", "Kuang", "Kui", "Kun", "Kuo",
            "La", "Lai", "Lan", "Lang", "Lao", "Le", "Lei", "Leng", "Li", "Lia", "Lian", "Liang",
            "Liao", "Lie", "Lin", "Ling", "Liu", "Long", "Lou", "Lu", "Lv", "Luan", "Lue", "Lun",
            "Luo", "Ma", "Mai", "Man", "Mang", "Mao", "Me", "Mei", "Men", "Meng", "Mi", "Mian",
            "Miao", "Mie", "Min", "Ming", "Miu", "Mo", "Mou", "Mu", "Na", "Nai", "Nan", "Nang",
            "Nao", "Ne", "Nei", "Nen", "Neng", "Ni", "Nian", "Niang", "Niao", "Nie", "Nin", "Ning",
            "Niu", "Nong", "Nu", "Nv", "Nuan", "Nue", "Nuo", "O", "Ou", "Pa", "Pai", "Pan",
            "Pang", "Pao", "Pei", "Pen", "Peng", "Pi", "Pian", "Piao", "Pie", "Pin", "Ping", "Po",
            "Pu", "Qi", "Qia", "Qian", "Qiang", "Qiao", "Qie", "Qin", "Qing", "Qiong", "Qiu", "Qu",
            "Quan", "Que", "Qun", "Ran", "Rang", "Rao", "Re", "Ren", "Reng", "Ri", "Rong", "Rou",
            "Ru", "Ruan", "Rui", "Run", "Ruo", "Sa", "Sai", "San", "Sang", "Sao", "Se", "Sen",
            "Seng", "Sha", "Shai", "Shan", "Shang", "Shao", "She", "Shen", "Sheng", "Shi", "Shou", "Shu",
            "Shua", "Shuai", "Shuan", "Shuang", "Shui", "Shun", "Shuo", "Si", "Song", "Sou", "Su", "Suan",
            "Sui", "Sun", "Suo", "Ta", "Tai", "Tan", "Tang", "Tao", "Te", "Teng", "Ti", "Tian",
            "Tiao", "Tie", "Ting", "Tong", "Tou", "Tu", "Tuan", "Tui", "Tun", "Tuo", "Wa", "Wai",
            "Wan", "Wang", "Wei", "Wen", "Weng", "Wo", "Wu", "Xi", "Xia", "Xian", "Xiang", "Xiao",
            "Xie", "Xin", "Xing", "Xiong", "Xiu", "Xu", "Xuan", "Xue", "Xun", "Ya", "Yan", "Yang",
            "Yao", "Ye", "Yi", "Yin", "Ying", "Yo", "Yong", "You", "Yu", "Yuan", "Yue", "Yun",
            "Za", "Zai", "Zan", "Zang", "Zao", "Ze", "Zei", "Zen", "Zeng", "Zha", "Zhai", "Zhan",
            "Zhang", "Zhao", "Zhe", "Zhen", "Zheng", "Zhi", "Zhong", "Zhou", "Zhu", "Zhua", "Zhuai", "Zhuan",
            "Zhuang", "Zhui", "Zhun", "Zhuo", "Zi", "Zong", "Zou", "Zu", "Zuan", "Zui", "Zun", "Zuo"
        };

        #endregion

        #region SpellCode(拼音区编码数组)

        /// <summary>
        /// 拼音区编码数组
        /// </summary>
        public static int[] SpellCode = new int[]
        {
            -20319, -20317, -20304, -20295, -20292, -20283, -20265, -20257, -20242, -20230, -20051, -20036,
            -20032, -20026, -20002, -19990, -19986, -19982, -19976, -19805, -19784, -19775, -19774, -19763,
            -19756, -19751, -19746, -19741, -19739, -19728, -19725, -19715, -19540, -19531, -19525, -19515,
            -19500, -19484, -19479, -19467, -19289, -19288, -19281, -19275, -19270, -19263, -19261, -19249,
            -19243, -19242, -19238, -19235, -19227, -19224, -19218, -19212, -19038, -19023, -19018, -19006,
            -19003, -18996, -18977, -18961, -18952, -18783, -18774, -18773, -18763, -18756, -18741, -18735,
            -18731, -18722, -18710, -18697, -18696, -18526, -18518, -18501, -18490, -18478, -18463, -18448,
            -18447, -18446, -18239, -18237, -18231, -18220, -18211, -18201, -18184, -18183, -18181, -18012,
            -17997, -17988, -17970, -17964, -17961, -17950, -17947, -17931, -17928, -17922, -17759, -17752,
            -17733, -17730, -17721, -17703, -17701, -17697, -17692, -17683, -17676, -17496, -17487, -17482,
            -17468, -17454, -17433, -17427, -17417, -17202, -17185, -16983, -16970, -16942, -16915, -16733,
            -16708, -16706, -16689, -16664, -16657, -16647, -16474, -16470, -16465, -16459, -16452, -16448,
            -16433, -16429, -16427, -16423, -16419, -16412, -16407, -16403, -16401, -16393, -16220, -16216,
            -16212, -16205, -16202, -16187, -16180, -16171, -16169, -16158, -16155, -15959, -15958, -15944,
            -15933, -15920, -15915, -15903, -15889, -15878, -15707, -15701, -15681, -15667, -15661, -15659,
            -15652, -15640, -15631, -15625, -15454, -15448, -15436, -15435, -15419, -15416, -15408, -15394,
            -15385, -15377, -15375, -15369, -15363, -15362, -15183, -15180, -15165, -15158, -15153, -15150,
            -15149, -15144, -15143, -15141, -15140, -15139, -15128, -15121, -15119, -15117, -15110, -15109,
            -14941, -14937, -14933, -14930, -14929, -14928, -14926, -14922, -14921, -14914, -14908, -14902,
            -14894, -14889, -14882, -14873, -14871, -14857, -14678, -14674, -14670, -14668, -14663, -14654,
            -14645, -14630, -14594, -14429, -14407, -14399, -14384, -14379, -14368, -14355, -14353, -14345,
            -14170, -14159, -14151, -14149, -14145, -14140, -14137, -14135, -14125, -14123, -14122, -14112,
            -14109, -14099, -14097, -14094, -14092, -14090, -14087, -14083, -13917, -13914, -13910, -13907,
            -13906, -13905, -13896, -13894, -13878, -13870, -13859, -13847, -13831, -13658, -13611, -13601,
            -13406, -13404, -13400, -13398, -13395, -13391, -13387, -13383, -13367, -13359, -13356, -13343,
            -13340, -13329, -13326, -13318, -13147, -13138, -13120, -13107, -13096, -13095, -13091, -13076,
            -13068, -13063, -13060, -12888, -12875, -12871, -12860, -12858, -12852, -12849, -12838, -12831,
            -12829, -12812, -12802, -12607, -12597, -12594, -12585, -12556, -12359, -12346, -12320, -12300,
            -12120, -12099, -12089, -12074, -12067, -12058, -12039, -11867, -11861, -11847, -11831, -11798,
            -11781, -11604, -11589, -11536, -11358, -11340, -11339, -11324, -11303, -11097, -11077, -11067,
            -11055, -11052, -11045, -11041, -11038, -11024, -11020, -11019, -11018, -11014, -10838, -10832,
            -10815, -10800, -10790, -10780, -10764, -10587, -10544, -10533, -10519, -10331, -10329, -10328,
            -10322, -10315, -10309, -10307, -10296, -10281, -10274, -10270, -10262, -10260, -10256, -10254
        };

        #endregion

        #region TimeFormatIso8601(时间格式化：ISO8601标准时间)

        /// <summary>
        /// 时间格式化：ISO8601标准时间
        /// </summary>
        public const string TimeFormatIso8601 = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'Z'";

        #endregion

        #region Mime

        /// <summary>
        /// MIME类型
        /// </summary>
        public static Dictionary<string, string> Mime => new Dictionary<string, string>()
        {
            {"3gp", "video/3gpp"},
            {"aab", "application/x-authoware-bin"},
            {"aam", "application/x-authoware-map"},
            {"aas", "application/x-authoware-seg"},
            {"ai", "application/postscript"},
            {"aif", "audio/x-aiff"},
            {"aifc", "audio/x-aiff"},
            {"aiff", "audio/x-aiff"},
            {"als", "audio/X-Alpha5"},
            {"amc", "application/x-mpeg"},
            {"ani", "application/octet-stream"},
            {"asc", "text/plain"},
            {"asd", "application/astound"},
            {"asf", "video/x-ms-asf"},
            {"asn", "application/astound"},
            {"asp", "application/x-asap"},
            {"asx", "video/x-ms-asf"},
            {"au", "audio/basic"},
            {"avb", "application/octet-stream"},
            {"avi", "video/x-msvideo"},
            {"awb", "audio/amr-wb"},
            {"bcpio", "application/x-bcpio"},
            {"bin", "application/octet-stream"},
            {"bld", "application/bld"},
            {"bld2", "application/bld2"},
            {"bmp", "application/x-MS-bmp"},
            {"bpk", "application/octet-stream"},
            {"bz2", "application/x-bzip2"},
            {"cal", "image/x-cals"},
            {"ccn", "application/x-cnc"},
            {"cco", "application/x-cocoa"},
            {"cdf", "application/x-netcdf"},
            {"cgi", "magnus-internal/cgi"},
            {"chat", "application/x-chat"},
            {"class", "application/octet-stream"},
            {"clp", "application/x-msclip"},
            {"cmx", "application/x-cmx"},
            {"co", "application/x-cult3d-object"},
            {"cod", "image/cis-cod"},
            {"cpio", "application/x-cpio"},
            {"cpt", "application/mac-compactpro"},
            {"crd", "application/x-mscardfile"},
            {"csh", "application/x-csh"},
            {"csm", "chemical/x-csml"},
            {"csml", "chemical/x-csml"},
            {"css", "text/css"},
            {"cur", "application/octet-stream"},
            {"dcm", "x-lml/x-evm"},
            {"dcr", "application/x-director"},
            {"dcx", "image/x-dcx"},
            {"dhtml", "text/html"},
            {"dir", "application/x-director"},
            {"dll", "application/octet-stream"},
            {"dmg", "application/octet-stream"},
            {"dms", "application/octet-stream"},
            {"doc", "application/msword"},
            {"dot", "application/x-dot"},
            {"dvi", "application/x-dvi"},
            {"dwf", "drawing/x-dwf"},
            {"dwg", "application/x-autocad"},
            {"dxf", "application/x-autocad"},
            {"dxr", "application/x-director"},
            {"ebk", "application/x-expandedbook"},
            {"emb", "chemical/x-embl-dl-nucleotide"},
            {"embl", "chemical/x-embl-dl-nucleotide"},
            {"eps", "application/postscript"},
            {"eri", "image/x-eri"},
            {"es", "audio/echospeech"},
            {"esl", "audio/echospeech"},
            {"etc", "application/x-earthtime"},
            {"etx", "text/x-setext"},
            {"evm", "x-lml/x-evm"},
            {"evy", "application/x-envoy"},
            {"exe", "application/octet-stream"},
            {"fh4", "image/x-freehand"},
            {"fh5", "image/x-freehand"},
            {"fhc", "image/x-freehand"},
            {"fif", "image/fif"},
            {"fm", "application/x-maker"},
            {"fpx", "image/x-fpx"},
            {"fvi", "video/isivideo"},
            {"gau", "chemical/x-gaussian-input"},
            {"gca", "application/x-gca-compressed"},
            {"gdb", "x-lml/x-gdb"},
            {"gif", "image/gif"},
            {"gps", "application/x-gps"},
            {"gtar", "application/x-gtar"},
            {"gz", "application/x-gzip"},
            {"hdf", "application/x-hdf"},
            {"hdm", "text/x-hdml"},
            {"hdml", "text/x-hdml"},
            {"hlp", "application/winhlp"},
            {"hqx", "application/mac-binhex40"},
            {"htm", "text/html"},
            {"html", "text/html"},
            {"hts", "text/html"},
            {"ice", "x-conference/x-cooltalk"},
            {"ico", "application/octet-stream"},
            {"ief", "image/ief"},
            {"ifm", "image/gif"},
            {"ifs", "image/ifs"},
            {"imy", "audio/melody"},
            {"ins", "application/x-NET-Install"},
            {"ips", "application/x-ipscript"},
            {"ipx", "application/x-ipix"},
            {"it", "audio/x-mod"},
            {"itz", "audio/x-mod"},
            {"ivr", "i-world/i-vrml"},
            {"j2k", "image/j2k"},
            {"jad", "text/vnd.sun.j2me.app-descriptor"},
            {"jam", "application/x-jam"},
            {"jar", "application/java-archive"},
            {"jnlp", "application/x-java-jnlp-file"},
            {"jpe", "image/jpeg"},
            {"jpeg", "image/jpeg"},
            {"jpg", "image/jpeg"},
            {"jpz", "image/jpeg"},
            {"js", "application/x-javascript"},
            {"jwc", "application/jwc"},
            {"kjx", "application/x-kjx"},
            {"lak", "x-lml/x-lak"},
            {"latex", "application/x-latex"},
            {"lcc", "application/fastman"},
            {"lcl", "application/x-digitalloca"},
            {"lcr", "application/x-digitalloca"},
            {"lgh", "application/lgh"},
            {"lha", "application/octet-stream"},
            {"lml", "x-lml/x-lml"},
            {"lmlpack", "x-lml/x-lmlpack"},
            {"lsf", "video/x-ms-asf"},
            {"lsx", "video/x-ms-asf"},
            {"lzh", "application/x-lzh"},
            {"m13", "application/x-msmediaview"},
            {"m14", "application/x-msmediaview"},
            {"m15", "audio/x-mod"},
            {"m3u", "audio/x-mpegurl"},
            {"m3url", "audio/x-mpegurl"},
            {"ma1", "audio/ma1"},
            {"ma2", "audio/ma2"},
            {"ma3", "audio/ma3"},
            {"ma5", "audio/ma5"},
            {"man", "application/x-troff-man"},
            {"map", "magnus-internal/imagemap"},
            {"mbd", "application/mbedlet"},
            {"mct", "application/x-mascot"},
            {"mdb", "application/x-msaccess"},
            {"mdz", "audio/x-mod"},
            {"me", "application/x-troff-me"},
            {"mel", "text/x-vmel"},
            {"mi", "application/x-mif"},
            {"mid", "audio/midi"},
            {"midi", "audio/midi"},
            {"mif", "application/x-mif"},
            {"mil", "image/x-cals"},
            {"mio", "audio/x-mio"},
            {"mmf", "application/x-skt-lbs"},
            {"mng", "video/x-mng"},
            {"mny", "application/x-msmoney"},
            {"moc", "application/x-mocha"},
            {"mocha", "application/x-mocha"},
            {"mod", "audio/x-mod"},
            {"mof", "application/x-yumekara"},
            {"mol", "chemical/x-mdl-molfile"},
            {"mop", "chemical/x-mopac-input"},
            {"mov", "video/quicktime"},
            {"movie", "video/x-sgi-movie"},
            {"mp2", "audio/x-mpeg"},
            {"mp3", "audio/x-mpeg"},
            {"mp4", "video/mp4"},
            {"mkv", "MKV-application/octet-stream"},
            {"vod", "application/vod"},
            {"ts", "video/ts"},
            {"mpc", "application/vnd.mpohun.certificate"},
            {"mpe", "video/mpeg"},
            {"mpeg", "video/mpeg"},
            {"mpg", "video/mpeg"},
            {"mpg4", "video/mp4"},
            {"mpga", "audio/mpeg"},
            {"mpn", "application/vnd.mophun.application"},
            {"mpp", "application/vnd.ms-project"},
            {"mps", "application/x-mapserver"},
            {"mrl", "text/x-mrml"},
            {"mrm", "application/x-mrm"},
            {"ms", "application/x-troff-ms"},
            {"mts", "application/metastream"},
            {"mtx", "application/metastream"},
            {"mtz", "application/metastream"},
            {"mzv", "application/metastream"},
            {"nar", "application/zip"},
            {"nbmp", "image/nbmp"},
            {"nc", "application/x-netcdf"},
            {"ndb", "x-lml/x-ndb"},
            {"ndwn", "application/ndwn"},
            {"nif", "application/x-nif"},
            {"nmz", "application/x-scream"},
            {"nokia-op-logo", "image/vnd.nok-oplogo-color"},
            {"npx", "application/x-netfpx"},
            {"nsnd", "audio/nsnd"},
            {"nva", "application/x-neva1"},
            {"oda", "application/oda"},
            {"oom", "application/x-AtlasMate-Plugin"},
            {"pac", "audio/x-pac"},
            {"pae", "audio/x-epac"},
            {"pan", "application/x-pan"},
            {"pbm", "image/x-portable-bitmap"},
            {"pcx", "image/x-pcx"},
            {"pda", "image/x-pda"},
            {"pdb", "chemical/x-pdb"},
            {"pdf", "application/pdf"},
            {"pfr", "application/font-tdpfr"},
            {"pgm", "image/x-portable-graymap"},
            {"pict", "image/x-pict"},
            {"pm", "application/x-perl"},
            {"pmd", "application/x-pmd"},
            {"png", "image/png"},
            {"pnm", "image/x-portable-anymap"},
            {"pnz", "image/png"},
            {"pot", "application/vnd.ms-powerpoint"},
            {"ppm", "image/x-portable-pixmap"},
            {"pps", "application/vnd.ms-powerpoint"},
            {"ppt", "application/vnd.ms-powerpoint"},
            {"pqf", "application/x-cprplayer"},
            {"pqi", "application/cprplayer"},
            {"prc", "application/x-prc"},
            {"proxy", "application/x-ns-proxy-autoconfig"},
            {"ps", "application/postscript"},
            {"ptlk", "application/listenup"},
            {"pub", "application/x-mspublisher"},
            {"pvx", "video/x-pv-pvx"},
            {"qcp", "audio/vnd.qcelp"},
            {"qt", "video/quicktime"},
            {"qti", "image/x-quicktime"},
            {"qtif", "image/x-quicktime"},
            {"r3t", "text/vnd.rn-realtext3d"},
            {"ra", "audio/x-pn-realaudio"},
            {"ram", "audio/x-pn-realaudio"},
            {"rar", "application/x-rar-compressed"},
            {"ras", "image/x-cmu-raster"},
            {"rdf", "application/rdf+xml"},
            {"rf", "image/vnd.rn-realflash"},
            {"rgb", "image/x-rgb"},
            {"rlf", "application/x-richlink"},
            {"rm", "audio/x-pn-realaudio"},
            {"rmf", "audio/x-rmf"},
            {"rmm", "audio/x-pn-realaudio"},
            {"rmvb", "audio/x-pn-realaudio"},
            {"rnx", "application/vnd.rn-realplayer"},
            {"roff", "application/x-troff"},
            {"rp", "image/vnd.rn-realpix"},
            {"rpm", "audio/x-pn-realaudio-plugin"},
            {"rt", "text/vnd.rn-realtext"},
            {"rte", "x-lml/x-gps"},
            {"rtf", "application/rtf"},
            {"rtg", "application/metastream"},
            {"rtx", "text/richtext"},
            {"rv", "video/vnd.rn-realvideo"},
            {"rwc", "application/x-rogerwilco"},
            {"s3m", "audio/x-mod"},
            {"s3z", "audio/x-mod"},
            {"sca", "application/x-supercard"},
            {"scd", "application/x-msschedule"},
            {"sdf", "application/e-score"},
            {"sea", "application/x-stuffit"},
            {"sgm", "text/x-sgml"},
            {"sgml", "text/x-sgml"},
            {"sh", "application/x-sh"},
            {"shar", "application/x-shar"},
            {"shtml", "magnus-internal/parsed-html"},
            {"shw", "application/presentations"},
            {"si6", "image/si6"},
            {"si7", "image/vnd.stiwap.sis"},
            {"si9", "image/vnd.lgtwap.sis"},
            {"sis", "application/vnd.symbian.install"},
            {"sit", "application/x-stuffit"},
            {"skd", "application/x-Koan"},
            {"skm", "application/x-Koan"},
            {"skp", "application/x-Koan"},
            {"skt", "application/x-Koan"},
            {"slc", "application/x-salsa"},
            {"smd", "audio/x-smd"},
            {"smi", "application/smil"},
            {"smil", "application/smil"},
            {"smp", "application/studiom"},
            {"smz", "audio/x-smd"},
            {"snd", "audio/basic"},
            {"spc", "text/x-speech"},
            {"spl", "application/futuresplash"},
            {"spr", "application/x-sprite"},
            {"sprite", "application/x-sprite"},
            {"spt", "application/x-spt"},
            {"src", "application/x-wais-source"},
            {"stk", "application/hyperstudio"},
            {"stm", "audio/x-mod"},
            {"sv4cpio", "application/x-sv4cpio"},
            {"sv4crc", "application/x-sv4crc"},
            {"svf", "image/vnd"},
            {"svg", "image/svg-xml"},
            {"svh", "image/svh"},
            {"svr", "x-world/x-svr"},
            {"swf", "application/x-shockwave-flash"},
            {"swfl", "application/x-shockwave-flash"},
            {"t", "application/x-troff"},
            {"tad", "application/octet-stream"},
            {"talk", "text/x-speech"},
            {"tar", "application/x-tar"},
            {"taz", "application/x-tar"},
            {"tbp", "application/x-timbuktu"},
            {"tbt", "application/x-timbuktu"},
            {"tcl", "application/x-tcl"},
            {"tex", "application/x-tex"},
            {"texi", "application/x-texinfo"},
            {"texinfo", "application/x-texinfo"},
            {"tgz", "application/x-tar"},
            {"thm", "application/vnd.eri.thm"},
            {"tif", "image/tiff"},
            {"tiff", "image/tiff"},
            {"tki", "application/x-tkined"},
            {"tkined", "application/x-tkined"},
            {"toc", "application/toc"},
            {"toy", "image/toy"},
            {"tr", "application/x-troff"},
            {"trk", "x-lml/x-gps"},
            {"trm", "application/x-msterminal"},
            {"tsi", "audio/tsplayer"},
            {"tsp", "application/dsptype"},
            {"tsv", "text/tab-separated-values"},
            {"ttf", "application/octet-stream"},
            {"ttz", "application/t-time"},
            {"txt", "text/plain"},
            {"ult", "audio/x-mod"},
            {"ustar", "application/x-ustar"},
            {"uu", "application/x-uuencode"},
            {"uue", "application/x-uuencode"},
            {"vcd", "application/x-cdlink"},
            {"vcf", "text/x-vcard"},
            {"vdo", "video/vdo"},
            {"vib", "audio/vib"},
            {"viv", "video/vivo"},
            {"vivo", "video/vivo"},
            {"vmd", "application/vocaltec-media-desc"},
            {"vmf", "application/vocaltec-media-file"},
            {"vmi", "application/x-dreamcast-vms-info"},
            {"vms", "application/x-dreamcast-vms"},
            {"vox", "audio/voxware"},
            {"vqe", "audio/x-twinvq-plugin"},
            {"vqf", "audio/x-twinvq"},
            {"vql", "audio/x-twinvq"},
            {"vre", "x-world/x-vream"},
            {"vrml", "x-world/x-vrml"},
            {"vrt", "x-world/x-vrt"},
            {"vrw", "x-world/x-vream"},
            {"vts", "workbook/formulaone"},
            {"wav", "audio/x-wav"},
            {"wax", "audio/x-ms-wax"},
            {"wbmp", "image/vnd.wap.wbmp"},
            {"web", "application/vnd.xara"},
            {"wi", "image/wavelet"},
            {"wis", "application/x-InstallShield"},
            {"wm", "video/x-ms-wm"},
            {"wma", "audio/x-ms-wma"},
            {"wmd", "application/x-ms-wmd"},
            {"wmf", "application/x-msmetafile"},
            {"wml", "text/vnd.wap.wml"},
            {"wmlc", "application/vnd.wap.wmlc"},
            {"wmls", "text/vnd.wap.wmlscript"},
            {"wmlsc", "application/vnd.wap.wmlscriptc"},
            {"wmlscript", "text/vnd.wap.wmlscript"},
            {"wmv", "audio/x-ms-wmv"},
            {"wmx", "video/x-ms-wmx"},
            {"wmz", "application/x-ms-wmz"},
            {"wpng", "image/x-up-wpng"},
            {"wpt", "x-lml/x-gps"},
            {"wri", "application/x-mswrite"},
            {"wrl", "x-world/x-vrml"},
            {"wrz", "x-world/x-vrml"},
            {"ws", "text/vnd.wap.wmlscript"},
            {"wsc", "application/vnd.wap.wmlscriptc"},
            {"wv", "video/wavelet"},
            {"wvx", "video/x-ms-wvx"},
            {"wxl", "application/x-wxl"},
            {"x-gzip", "application/x-gzip"},
            {"xar", "application/vnd.xara"},
            {"xbm", "image/x-xbitmap"},
            {"xdm", "application/x-xdma"},
            {"xdma", "application/x-xdma"},
            {"xdw", "application/vnd.fujixerox.docuworks"},
            {"xht", "application/xhtml+xml"},
            {"xhtm", "application/xhtml+xml"},
            {"xhtml", "application/xhtml+xml"},
            {"xla", "application/vnd.ms-excel"},
            {"xlc", "application/vnd.ms-excel"},
            {"xll", "application/x-excel"},
            {"xlm", "application/vnd.ms-excel"},
            {"xls", "application/vnd.ms-excel"},
            {"xlt", "application/vnd.ms-excel"},
            {"xlw", "application/vnd.ms-excel"},
            {"xm", "audio/x-mod"},
            {"xml", "text/xml"},
            {"xmz", "audio/x-mod"},
            {"xpi", "application/x-xpinstall"},
            {"xpm", "image/x-xpixmap"},
            {"xsit", "text/xml"},
            {"xsl", "text/xml"},
            {"xul", "text/xul"},
            {"xwd", "image/x-xwindowdump"},
            {"xyz", "chemical/x-pdb"},
            {"yz1", "application/x-yz1"},
            {"z", "application/x-compress"},
            {"zac", "application/x-zaurus-zac"},
            {"zip", "application/zip"}
        };

        #endregion
    }
}