//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Extras.Applications.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Util.Extras.Applications.Properties.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CreateRequestIsEmpty {
            get {
                return ResourceManager.GetString("CreateRequestIsEmpty", resourceCulture);
            }
        }
        
        public static string IdIsEmpty {
            get {
                return ResourceManager.GetString("IdIsEmpty", resourceCulture);
            }
        }
        
        public static string ParentIdIsEmpty {
            get {
                return ResourceManager.GetString("ParentIdIsEmpty", resourceCulture);
            }
        }
        
        public static string QueryIsEmpty {
            get {
                return ResourceManager.GetString("QueryIsEmpty", resourceCulture);
            }
        }
        
        public static string RequestIsEmpty {
            get {
                return ResourceManager.GetString("RequestIsEmpty", resourceCulture);
            }
        }
        
        public static string UpdateRequestIsEmpty {
            get {
                return ResourceManager.GetString("UpdateRequestIsEmpty", resourceCulture);
            }
        }
    }
}
